### ISSUE TITLE
template blue and black has the same color

### ISSUE THREAD

**Issue by twnaing** [tinted-theming/base16-vivid#2]
https://github.com/tinted-theming/base16-vivid/blob/a2193d6b0c7e9357025e9c7ee344b917d7800b03/templates/default.mustache#L8-L12

That makes ls of image invisible with base16-shell. Changing blue to `base0D` works the same as vivid built-in colors.

**Comment by arunoruto** [comment]
Thanks for the notice! Seems like i overlooked when generating the config..
If you got any further problems, feel free to create a new PR!
